package com.example.cx.icxrobot.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.cx.icxrobot.entry.User;
import com.example.cx.icxrobot.entry.ChatMessage;

import com.example.cx.icxrobot.greendao.UserDao;
import com.example.cx.icxrobot.greendao.ChatMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig chatMessageDaoConfig;

    private final UserDao userDao;
    private final ChatMessageDao chatMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        chatMessageDaoConfig = daoConfigMap.get(ChatMessageDao.class).clone();
        chatMessageDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        chatMessageDao = new ChatMessageDao(chatMessageDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(ChatMessage.class, chatMessageDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        chatMessageDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ChatMessageDao getChatMessageDao() {
        return chatMessageDao;
    }

}
